{:user {:plugins [[cider/cider-nrepl "0.7.0"]
                  [codox "0.8.10"]
                  [jonase/eastwood "0.1.4"]
                  [lein-iclojure "1.2"]
                  [lein-kibit "0.0.8"]
                  [lein-light-nrepl "0.0.18"]
                  [lein-marginalia "0.7.1"]
                  ;[lein-swank "1.4.5"]
                  ;[lein-noir "1.2.1"]
                 ]}}
