{:user {:plugins [[cider/cider-nrepl "0.8.2"]
                  [codox "0.8.11"]
                  [jonase/eastwood "0.2.1"]
                  [lein-datomic "0.2.0"]
                  [lein-iclojure "1.2"]
                  [lein-kibit "0.0.8"]
                  [lein-light-nrepl "0.1.0"]
                  [lein-marginalia "0.8.0"]
                  ;[lein-swank "1.4.5"]
                  ;[lein-noir "1.2.1"]
                  [refactor-nrepl "1.0.1"]
                 ]
        ;:datomic {:install-location "/Users/tapichu/Downloads/datomic-free-0.9.4699"}}}
        :dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.nrepl "0.2.7"]]}}
