# If not running interactively, do not do anything
[[ "$-" != *i* ]] && return
# [[ -z "$TMUX" ]] && exec tmux
tmux has-session -t $USER 2>/dev/null || tmux new-session -d -s $USER

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
# http://www.bergspot.com/blog/2012/02/how-to-fix-warning-setlocale-lc_ctype-cannot-change-locale-utf-8/
export LC_CTYPE="en_US.UTF-8"

#PS1='\h:\W \u\$'
PS1='\u@\h:\W$(__git_ps1 " (%s)")> '
export PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

export EDITOR=vim

export PYTHON_PREFIX=/usr/local
export NODE_PATH=/usr/local/lib/node_modules
export CLOJURESCRIPT_HOME=$HOME/code/clojure/clojurescript
export PATH=$CLOJURESCRIPT_HOME/bin:$PATH

# Aliases
test -s ~/.alias && source ~/.alias || true

# Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# Bash VI mode
# http://www.jukie.net/bart/blog/20040326082602
set -o vi
set editing-mode vi
set keymap vi
set convert-meta on
# ^p check for partial match in history
bind -m vi-insert "\C-p":dynamic-complete-history
# ^n cycle through the list of partial matches
bind -m vi-insert "\C-n":menu-complete
# ^l clear screen
bind -m vi-insert "\C-l":clear-screen
bind -m vi-command "\C-l":clear-screen

# Git
export LESS="-erX"
export GIT_PS1_SHOWDIRTYSTATE=true

# Git prompt
if [ -f /usr/local/etc/bash_completion.d/git-prompt.sh ]; then
    . /usr/local/etc/bash_completion.d/git-prompt.sh
fi

# Easily jump around the file system by manually adding marks
# marks are stored as symbolic links in the directory $MARKPATH (default $HOME/.marks)
#
# jump FOO: jump to a mark named FOO
# mark FOO: create a mark named FOO
# unmark FOO: delete a mark
# marks: lists all marks

export MARKPATH=$HOME/.marks
function jump {
    cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark {
    mkdir -p "$MARKPATH"; ln -s "$(pwd)" $MARKPATH/$1
}
function unmark {
    rm -i "$MARKPATH/$1"
}
function marks {
    ls -l "$MARKPATH" | gsed 's/  / /g' | cut -d' ' -f9- | gsed 's/ -/\t-/g' && echo
}

function _completemarks {
    COMPREPLY=($(ls $MARKPATH | grep "$2"))
}

complete -F _completemarks jump
complete -F _completemarks unmark

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
